"""
app/schemas/chat.py
Pydantic v2 schemas for the AI Health Assistant chatbot.
"""

from typing import Optional
from pydantic import BaseModel, Field


class ChatMessage(BaseModel):
    role: str = Field(..., examples=["user", "assistant"])
    content: str


class ChatRequest(BaseModel):
    user_id: Optional[str] = None
    scan_id: Optional[str] = None
    message: str = Field(..., min_length=1, max_length=1000)
    history: list[ChatMessage] = Field(default_factory=list, max_length=20)


class ChatResponse(BaseModel):
    reply: str
    disclaimer: str = (
        "⚠️ This response is generated by an AI system for educational purposes only. "
        "It does NOT constitute medical advice, diagnosis, or treatment. "
        "Always consult a qualified dermatologist or healthcare professional."
    )
